# Base configs
baseurl:
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Sam Allen"
subtitle: "See the world through my eyes!"
author: "Sam Allen"
header:
 title: "Photography"
 subtitle: "by Sam Allen"
footer:
 name: "Hey! I'm Sam."
 bio: "I am a developer and a tech aficionado from India. Love making teeny tiny apps solving tiny problems in life and now learning photography."
#web_design:
#social_urls:
#facebook: 
#twitter:
#instagram:
#dribbble:
#linkedin:
#github:
